apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: vault.sudojoss.com
    http:
      paths:
        - path: /
          backend:
            serviceName: vault
            servicePort: 8200