apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: jupyter-notebook
  volumeMode: Filesystem
  volumeName: jupyter-notebook
status: {}
