apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
  name: nextcloud-config-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nextcloud-config
  volumeMode: Filesystem
  volumeName: nextcloud-config
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
  name: nextcloud-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nextcloud-data
  volumeMode: Filesystem
  volumeName: nextcloud-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
  name: nextcloud-local-home-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nextcloud-local-home
  volumeMode: Filesystem
  volumeName: nextcloud-local-home
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-db
  name: nextcloud-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nextcloud-db
  volumeMode: Filesystem
  volumeName: nextcloud-db
status: {}
