kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis
spec:
  storageClassName: redis
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
  name: redis
  namespace: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis
  volumeMode: Filesystem
  volumeName: redis
status: {}
